apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-data-deployment
  labels:
    app: employee-data
spec:
  replicas: 3  # Scaling: you can adjust this value
  selector:
    matchLabels:
      app: employee-data
  template:
    metadata:
      labels:
        app: employee-data
    spec:
      containers:
      - name: employee-data-container
        image: myrepo/employee-data:latest  # Replace with your image name
        ports:
        - containerPort: 5000
        # Liveness probe: Checks that your application is healthy.
        livenessProbe:
          httpGet:
            path: /health   # Ensure your app provides a health endpoint or adjust accordingly
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        # Readiness probe: Checks that your app is ready to serve traffic.
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
