apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-inference-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/model-inference
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-inference-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-inference
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-inference
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      containers:
      - name: model-inference
        image: myrepo-model-inference:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: model-data
          mountPath: /app/models
      volumes:
      - name: model-data
        persistentVolumeClaim:
          claimName: model-inference-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: model-inference-service
spec:
  selector:
    app: model-inference
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
